<?php

/**
 * BaseDevice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $type
 * @property string $device
 * @property decimal $lat
 * @property decimal $lon
 * @property integer $city_id
 * @property SxGeoCity $City
 * 
 * @method string    getName()    Returns the current record's "name" value
 * @method string    getType()    Returns the current record's "type" value
 * @method string    getDevice()  Returns the current record's "device" value
 * @method decimal   getLat()     Returns the current record's "lat" value
 * @method decimal   getLon()     Returns the current record's "lon" value
 * @method integer   getCityId()  Returns the current record's "city_id" value
 * @method SxGeoCity getCity()    Returns the current record's "City" value
 * @method Device    setName()    Sets the current record's "name" value
 * @method Device    setType()    Sets the current record's "type" value
 * @method Device    setDevice()  Sets the current record's "device" value
 * @method Device    setLat()     Sets the current record's "lat" value
 * @method Device    setLon()     Sets the current record's "lon" value
 * @method Device    setCityId()  Sets the current record's "city_id" value
 * @method Device    setCity()    Sets the current record's "City" value
 * 
 * @package    erotic-massage-egostudio
 * @subpackage model
 * @author     Vasilisa the Wise
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDevice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('device', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('lat', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 7,
             'length' => 10,
             ));
        $this->hasColumn('lon', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 7,
             'length' => 10,
             ));
        $this->hasColumn('city_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SxGeoCity as City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}