<?php

/**
 * BaseSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $project_name
 * @property string $email
 * @property string $logo
 * 
 * @method string   getProjectName()  Returns the current record's "project_name" value
 * @method string   getEmail()        Returns the current record's "email" value
 * @method string   getLogo()         Returns the current record's "logo" value
 * @method Settings setProjectName()  Sets the current record's "project_name" value
 * @method Settings setEmail()        Sets the current record's "email" value
 * @method Settings setLogo()         Sets the current record's "logo" value
 * 
 * @package    erotic-massage-egostudio
 * @subpackage model
 * @author     Vasilisa the Wise
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('settings');
        $this->hasColumn('project_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}