<?php

/**
 * BaseArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $name_en
 * @property decimal $lat
 * @property decimal $lon
 * @property boolean $public
 * @property Doctrine_Collection $SxGeoCity
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getNameEn()    Returns the current record's "name_en" value
 * @method decimal             getLat()       Returns the current record's "lat" value
 * @method decimal             getLon()       Returns the current record's "lon" value
 * @method boolean             getPublic()    Returns the current record's "public" value
 * @method Doctrine_Collection getSxGeoCity() Returns the current record's "SxGeoCity" collection
 * @method Area                setName()      Sets the current record's "name" value
 * @method Area                setNameEn()    Sets the current record's "name_en" value
 * @method Area                setLat()       Sets the current record's "lat" value
 * @method Area                setLon()       Sets the current record's "lon" value
 * @method Area                setPublic()    Sets the current record's "public" value
 * @method Area                setSxGeoCity() Sets the current record's "SxGeoCity" collection
 * 
 * @package    erotic-massage-egostudio
 * @subpackage model
 * @author     Vasilisa the Wise
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('area');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name_en', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('lat', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 7,
             'length' => 10,
             ));
        $this->hasColumn('lon', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 7,
             'length' => 10,
             ));
        $this->hasColumn('public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SxGeoCity', array(
             'local' => 'id',
             'foreign' => 'area_id'));
    }
}