<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $anonce
 * @property string $text
 * @property string $img
 * @property string $title
 * @property string $keywords
 * @property string $metadesc
 * @property boolean $public
 * 
 * @method string  getName()     Returns the current record's "name" value
 * @method string  getAnonce()   Returns the current record's "anonce" value
 * @method string  getText()     Returns the current record's "text" value
 * @method string  getImg()      Returns the current record's "img" value
 * @method string  getTitle()    Returns the current record's "title" value
 * @method string  getKeywords() Returns the current record's "keywords" value
 * @method string  getMetadesc() Returns the current record's "metadesc" value
 * @method boolean getPublic()   Returns the current record's "public" value
 * @method Post    setName()     Sets the current record's "name" value
 * @method Post    setAnonce()   Sets the current record's "anonce" value
 * @method Post    setText()     Sets the current record's "text" value
 * @method Post    setImg()      Sets the current record's "img" value
 * @method Post    setTitle()    Sets the current record's "title" value
 * @method Post    setKeywords() Sets the current record's "keywords" value
 * @method Post    setMetadesc() Sets the current record's "metadesc" value
 * @method Post    setPublic()   Sets the current record's "public" value
 * 
 * @package    erotic-massage-egostudio
 * @subpackage model
 * @author     Vasilisa the Wise
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('anonce', 'string', 2147483647, array(
             'type' => 'string',
             'length' => 2147483647,
             ));
        $this->hasColumn('text', 'string', 2147483647, array(
             'type' => 'string',
             'length' => 2147483647,
             ));
        $this->hasColumn('img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('metadesc', 'string', 2147483647, array(
             'type' => 'string',
             'length' => 2147483647,
             ));
        $this->hasColumn('public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             'builder' => 
             array(
              0 => 'SlugifyClass',
              1 => 'Slugify',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}