<?php

/**
 * BaseGirl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $city_id
 * @property string $name
 * @property string $content
 * @property string $img
 * @property boolean $public
 * @property SxGeoCity $City
 * 
 * @method integer   getCityId()  Returns the current record's "city_id" value
 * @method string    getName()    Returns the current record's "name" value
 * @method string    getContent() Returns the current record's "content" value
 * @method string    getImg()     Returns the current record's "img" value
 * @method boolean   getPublic()  Returns the current record's "public" value
 * @method SxGeoCity getCity()    Returns the current record's "City" value
 * @method Girl      setCityId()  Sets the current record's "city_id" value
 * @method Girl      setName()    Sets the current record's "name" value
 * @method Girl      setContent() Sets the current record's "content" value
 * @method Girl      setImg()     Sets the current record's "img" value
 * @method Girl      setPublic()  Sets the current record's "public" value
 * @method Girl      setCity()    Sets the current record's "City" value
 * 
 * @package    erotic-massage-egostudio
 * @subpackage model
 * @author     Vasilisa the Wise
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGirl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('girl');
        $this->hasColumn('city_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 2147483647, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2147483647,
             ));
        $this->hasColumn('img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SxGeoCity as City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'city_id',
             ),
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             'builder' => 
             array(
              0 => 'SlugifyClass',
              1 => 'Slugify',
             ),
             ));
        $this->actAs($sortable0);
        $this->actAs($sluggable0);
    }
}