<?php

/**
 * BaseSocial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $city_id
 * @property string $twitter
 * @property string $instagram
 * @property string $facebook
 * @property string $vk
 * @property SxGeoCity $City
 * 
 * @method integer   getCityId()    Returns the current record's "city_id" value
 * @method string    getTwitter()   Returns the current record's "twitter" value
 * @method string    getInstagram() Returns the current record's "instagram" value
 * @method string    getFacebook()  Returns the current record's "facebook" value
 * @method string    getVk()        Returns the current record's "vk" value
 * @method SxGeoCity getCity()      Returns the current record's "City" value
 * @method Social    setCityId()    Sets the current record's "city_id" value
 * @method Social    setTwitter()   Sets the current record's "twitter" value
 * @method Social    setInstagram() Sets the current record's "instagram" value
 * @method Social    setFacebook()  Sets the current record's "facebook" value
 * @method Social    setVk()        Sets the current record's "vk" value
 * @method Social    setCity()      Sets the current record's "City" value
 * 
 * @package    erotic-massage-egostudio
 * @subpackage model
 * @author     Vasilisa the Wise
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSocial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('social');
        $this->hasColumn('city_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('twitter', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('instagram', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('facebook', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('vk', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SxGeoCity as City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}