<?php

/**
 * CitySetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    erotic-massage-egostudio
 * @subpackage model
 * @author     Vasilisa the Wise
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CitySetting extends BaseCitySetting
{
}
