<?php

/**
 * CitySettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CitySettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CitySettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CitySetting');
    }
}