<?php

/**
 * CollectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Collection');
    }
    public static function getCollections()
    {
      return  self::getInstance()->createQuery('c')
	      ->where('c.public = 1')           
	      ->orderBy('c.position')
	      ->execute();
    }    
}
