<?php

/**
 * GirlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GirlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GirlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Girl');
    }
    public static function getGirlsByCityAndUser($city_id)
    {
      return  self::getInstance()->createQuery('g')
	      ->where('g.public = 1')   
	      ->andWhere('LENGTH(g.img) > 0')           
          ->andWhereIn('g.city_id',array($city_id,222))
          ->orderBy('g.position')
	      ->execute();
    }          
}
