<?php

/**
 * PostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Post');
    }
    public static function getPostsItem()
    {
      return  self::getInstance()->createQuery('p')
	      ->select('p.*')
	      ->where('p.public = 1')   
//	      ->addWhere('LENGTH(p.img) > 0')          
	      ->orderBy('p.created_at desc');
    }       
}
