<?php

/**
 * ServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Service');
    }
    public static function getServicesByCity()
    {
      return  self::getInstance()->createQuery('s')
	      ->where('s.public = 1')   
          ->orderBy('s.position')
	      ->execute();
    }  


/**
 * frontend, list services
 */
    public static function getServicesByCityAndUser($city_id)
    {
      return  self::getInstance()->createQuery('s')
	      ->select('s.*, LENGTH(s.img) length_img')
	      ->where('s.public = 1')   
	      ->andWhere('LENGTH(s.img) > 0')           
          ->andWhere('s.city_id = ?',$city_id)
          //->andWhereIn('s.city_id',array($city_id,222))
          ->orderBy('s.position')
	      ->execute();
    }        
}
