<?php

/**
 * SxGeoCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SxGeoCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SxGeoCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SxGeoCity');
    }

    public static function getCityActive()
    {
      return  self::getInstance()->createQuery('c')
	      ->where('c.public_active = 1')
          ->orderBy('c.name')
	      ->execute();
    }   


  public function retrieveCitySetting(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->select( $rootAlias . '.*, c.telephone telephone, c.telephone2 telephone2')
    ->leftJoin($rootAlias  . '.Cities c')
    ->where( $rootAlias . '.public_active = 1');
    return $q;
  }
    

}
