# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    
    - fontello.css
    - skeleton.css
    - base.css
    - fotorama.css
    - owl.carousel.css
    - animate.css
    - magnific-popup.css
    - timepicker.css
    - datepicker.css
    - style.css
  javascripts:
    - jquery.js
    - carousel.js
    - plugins.js
    - ie8.js: {condition: 'lt IE 10'}    
    - init.js
  has_layout:     true
  layout:         layout
