generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Area
    theme:                 board
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          area
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Области       
        max_per_page:  50
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
