 #default:
 # stylesheets:  
 #   - /assets/global/plugins/font-awesome/css/font-awesome.min.css
 # javascripts:
 #   - /assets/global/plugins/respond.min.js
all:
  components:
    breadcrumb: [collection,breadcrumb]
  stylesheets:  
    - /csDoctrineActAsSortablePlugin/css/sortable.css    
