all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=egostudio
      username: root
      password:
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8
