 #default:
 # stylesheets:  
 #   - /assets/global/plugins/font-awesome/css/font-awesome.min.css
 # javascripts:
 #   - /assets/global/plugins/respond.min.js
all:
  components:
    breadcrumb: [settings,breadcrumb]
